# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1496663251);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1496663371);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1500235700);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1496663131);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1489737445);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1496663491);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.slowStartup.averageTime", 6303);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20151016093648");
user_pref("browser.startup.homepage_override.mstone", "41.0.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1508173358487");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1508173363161");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1508259763161");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1487341824242");
user_pref("datareporting.policy.firstRunTime", "1487341760182");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.firstPaint", 5795);
user_pref("datareporting.sessions.current.main", 780);
user_pref("datareporting.sessions.current.sessionRestored", 6288);
user_pref("datareporting.sessions.current.startTime", "1508173291951");
user_pref("datareporting.sessions.current.totalTime", 52);
user_pref("datareporting.sessions.currentIndex", 8);
user_pref("datareporting.sessions.prunedIndex", 7);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:41.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1496663262);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20170302.01");
user_pref("extensions.lastAppVersion", "41.0.2");
user_pref("extensions.lastPlatformVersion", "41.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"41.0.2\",\"st\":1445442923000,\"mt\":1444992106000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597402000}}}");
user_pref("gecko.buildID", "20151016093648");
user_pref("gecko.mstone", "41.0.2");
user_pref("idle.lastDailyNotification", 1508173398);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1487341830);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20151016093648");
user_pref("media.gmp-manager.lastCheck", 1508173363);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 52452);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1508173292);
user_pref("toolkit.telemetry.cachedClientID", "f22612a1-a5e7-4a1e-8e7a-301f73417e63");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
